name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Security audit
      run: npm audit --audit-level=high

    - name: Run linting
      run: npx eslint . --ext .js,.jsx,.ts,.tsx

    - name: Run formatting check
      run: npx prettier --check .

    - name: Run tests
      run: npm test

    - name: Build
      run: npm run build

    # Add deployment steps here if needed
    # - name: Deploy
    #   if: github.ref == 'refs/heads/main'
    #   run: echo "Add deployment commands here"